# -*- coding: utf-8 -*-
"""People Flow Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrjD8yFPj1ELoL4YTvWFTgUAgiBfVV5y
"""

!pip install ultralytics supervision

# ============================================================
# People Flow Detection - Full Project
# ============================================================
# Install first (run this in Colab or terminal):
# !pip install ultralytics supervision opencv-python numpy matplotlib
# ============================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO
import supervision as sv

# ============================================================
# STEP 1: LOAD MODEL
# ============================================================

# Load YOLOv8 nano model (smallest & fastest)
# It will auto-download yolov8n.pt on first run
model = YOLO("yolov8n.pt")

# ============================================================
# STEP 2: SETUP TRACKER
# ============================================================

# ByteTrack gives each person a unique ID across frames
tracker = sv.ByteTrack()

# ============================================================
# STEP 3: OPEN VIDEO
# ============================================================

VIDEO_URL = "https://media.roboflow.com/supervision/video-examples/people-walking.mp4"

cap = cv2.VideoCapture(VIDEO_URL)

# Get video properties
WIDTH  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
HEIGHT = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
FPS    = int(cap.get(cv2.CAP_PROP_FPS))

print(f"Video: {WIDTH}x{HEIGHT} @ {FPS}fps")

# ============================================================
# STEP 4: DEFINE COUNTING LINES
# ============================================================
# LINE 1 (green)  = upper line → crossing DOWN = IN
# LINE 2 (red)    = lower line → crossing UP   = OUT
#
# These y-coordinates are for this specific video
# Use https://polygonzone.roboflow.com/ to get your own

LINE1_Y = int(HEIGHT * 0.40)   #40% from top = up per line
LINE2_Y = int(HEIGHT * 0.65)   # 65% from top = lower line

# ============================================================
# STEP 5: SETUP OUTPUT VIDEO WRITER
# ============================================================

out = cv2.VideoWriter(
    "output.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    FPS,
    (WIDTH, HEIGHT)
)

# ============================================================
# STEP 6: COUNTING VARIABLES
# ============================================================

count_in  = 0   # People who moved DOWN across LINE1
count_out = 0   # People who moved UP   across LINE2

# Dictionary to remember each person's previous y position
# Key = tracker ID,  Value = previous center_y
prev_positions = {}

# Set to remember IDs already counted (avoid double counting)
already_counted_in  = set()
already_counted_out = set()

# ============================================================
# STEP 7: HEATMAP ACCUMULATOR
# ============================================================

# Empty black image — same size as video
# We will add +1 wherever a person stands, every frame
heatmap_accumulator = np.zeros((HEIGHT, WIDTH), dtype=np.float32)

# ============================================================
# STEP 8: MAIN PROCESSING LOOP
# ============================================================

frame_count = 0

while True:

    # --- Read one frame ---
    ret, frame = cap.read()
    if not ret:
        break   # No more frames → stop

    frame_count += 1

    # --- Run YOLO detection ---
    results = model(frame, verbose=False)[0]   # verbose=False = no console spam

    # --- Convert YOLO results to Supervision format ---
    detections = sv.Detections.from_ultralytics(results)

    # --- Keep only CLASS 0 = person ---
    detections = detections[detections.class_id == 0]

    # --- Run tracker → assigns unique tracker_id to each person ---
    detections = tracker.update_with_detections(detections)

    # ============================================================
    # STEP 9: COUNTING LOGIC + HEATMAP UPDATE
    # ============================================================

    for i in range(len(detections)):

        # Get bounding box corners
        x1, y1, x2, y2 = map(int, detections.xyxy[i])

        # Calculate center point of the bounding box
        cx = (x1 + x2) // 2   # center x
        cy = (y1 + y2) // 2   # center y

        # Get this person's unique ID
        tracker_id = int(detections.tracker_id[i])

        # --- Update heatmap ---
        # Add a dot at this person's center position
        heatmap_accumulator[cy, cx] += 1

        # --- Counting logic ---
        if tracker_id in prev_positions:

            prev_y = prev_positions[tracker_id]   # where they were last frame

            # IN: person moved DOWN (y increases) and crossed LINE1
            if prev_y < LINE1_Y and cy >= LINE1_Y:
                if tracker_id not in already_counted_in:
                    count_in += 1
                    already_counted_in.add(tracker_id)

            # OUT: person moved UP (y decreases) and crossed LINE2
            if prev_y > LINE2_Y and cy <= LINE2_Y:
                if tracker_id not in already_counted_out:
                    count_out += 1
                    already_counted_out.add(tracker_id)

        # Remember this person's current y for next frame
        prev_positions[tracker_id] = cy

        # --- Draw bounding box ---
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # --- Draw tracker ID above the box ---
        cv2.putText(frame, f"ID:{tracker_id}",
                    (x1, y1 - 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        # --- Draw center dot ---
        cv2.circle(frame, (cx, cy), 4, (0, 255, 255), -1)

    # ============================================================
    # STEP 10: DRAW LINES AND COUNTERS ON FRAME
    # ============================================================

    # Draw LINE 1 (green = IN line)
    cv2.line(frame, (0, LINE1_Y), (WIDTH, LINE1_Y), (0, 255, 0), 2)
    cv2.putText(frame, "IN LINE",
                (10, LINE1_Y - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # Draw LINE 2 (red = OUT line)
    cv2.line(frame, (0, LINE2_Y), (WIDTH, LINE2_Y), (0, 0, 255), 2)
    cv2.putText(frame, "OUT LINE",
                (10, LINE2_Y - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

    # Draw IN / OUT counter box (top-left corner)
    cv2.rectangle(frame, (5, 5), (200, 70), (0, 0, 0), -1)       # black background
    cv2.putText(frame, f"IN  : {count_in}",
                (15, 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
    cv2.putText(frame, f"OUT : {count_out}",
                (15, 60),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)

    # --- Save this frame to output video ---
    out.write(frame)

    # --- Progress update every 50 frames ---
    if frame_count % 50 == 0:
        print(f"Processed {frame_count} frames | IN={count_in} OUT={count_out}")

# ============================================================
# STEP 11: RELEASE VIDEO FILES
# ============================================================

cap.release()
out.release()
print(f"\nVideo saved! Total frames: {frame_count}")
print(f"Final count → IN: {count_in} | OUT: {count_out}")

# ============================================================
# STEP 12: GENERATE AND SAVE HEATMAP
# ============================================================

# Blur the heatmap so dots become smooth blobs
heatmap_blur = cv2.GaussianBlur(heatmap_accumulator, (51, 51), 0)

# Normalize to 0-255 range so we can apply color
heatmap_norm = cv2.normalize(heatmap_blur, None, 0, 255, cv2.NORM_MINMAX)
heatmap_uint8 = np.uint8(heatmap_norm)

# Apply color map: blue=low activity, red=high activity
heatmap_colored = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET)

# Save the heatmap image
cv2.imwrite("heatmap.png", heatmap_colored)
print("Heatmap saved as heatmap.png")

# Show heatmap using matplotlib (works in Colab)
plt.figure(figsize=(12, 6))
plt.imshow(cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB))
plt.title("People Flow Heatmap\n(Red = High Traffic | Blue = Low Traffic)")
plt.axis("off")
plt.tight_layout()
plt.savefig("heatmap_display.png", dpi=150)
plt.show()
print("All done!")

